version: '2'
services:
  mongo:
    image: hub.c.163.com/library/mongo:3.2
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  app:
    image: hub.c.163.com/bingohuang/12factor-app:1.0
    ports:
      - "1337:1337"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/12factor-app
volumes:
  mongo-data:
